[build]
default-target = "x86_64-unknown-linux-gnu"
pre-build = ["apt-get update"]              # can also be the path to a file to run

# 编译 x86_64-apple-darwin
[target.x86_64-apple-darwin]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge"
pre-build = [
    "rustup target add x86_64-apple-darwin",
    "curl -L https://github.com/roblabla/MacOSX-SDKs/releases/download/13.3/MacOSX13.3.sdk.tar.xz | tar xJ",
    "export SDKROOT=$(pwd)/MacOSX13.3.sdk/",
    "export CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER=rust-lld",
]

# 编译 aarch64-apple-darwin
[target.aarch64-apple-darwin]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"
pre-build = [
    "rustup target add aarch64-apple-darwin",
    "curl -L https://github.com/roblabla/MacOSX-SDKs/releases/download/13.3/MacOSX13.3.sdk.tar.xz | tar xJ",
    "export SDKROOT=$(pwd)/MacOSX13.3.sdk/",
    "export CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=rust-lld",
]
