[build]
default-target = "x86_64-unknown-linux-gnu"
pre-build = ["apt-get update"]              # can also be the path to a file to run

# 编译 x86_64-apple-darwin
[target.x86_64-apple-darwin]
linker = "rust-lld"
runner = "cargo"
pre-build = [
    "curl -L https://github.com/roblabla/MacOSX-SDKs/releases/download/13.3/MacOSX13.3.sdk.tar.xz | tar xJ",
    "export SDKROOT=$(pwd)/MacOSX13.3.sdk/",
]

# 编译 aarch64-apple-darwin
[target.aarch64-apple-darwin]
linker = "rust-lld"
runner = "cargo"
pre-build = [
    "curl -L https://github.com/roblabla/MacOSX-SDKs/releases/download/13.3/MacOSX13.3.sdk.tar.xz | tar xJ",
    "export SDKROOT=$(pwd)/MacOSX13.3.sdk/",
]
